// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebSite.proto

package com.pkslow.proto;

public final class PkslowWebSite {
  private PkslowWebSite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebSiteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebSite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string link = 2;</code>
     * @return The link.
     */
    java.lang.String getLink();
    /**
     * <code>string link = 2;</code>
     * @return The bytes for link.
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>.WebSite.Server server = 4;</code>
     * @return Whether the server field is set.
     */
    boolean hasServer();
    /**
     * <code>.WebSite.Server server = 4;</code>
     * @return The server.
     */
    com.pkslow.proto.PkslowWebSite.WebSite.Server getServer();
    /**
     * <code>.WebSite.Server server = 4;</code>
     */
    com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder getServerOrBuilder();
  }
  /**
   * Protobuf type {@code WebSite}
   */
  public static final class WebSite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WebSite)
      WebSiteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebSite.newBuilder() to construct.
    private WebSite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebSite() {
      name_ = "";
      link_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebSite();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WebSite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              link_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder subBuilder = null;
              if (server_ != null) {
                subBuilder = server_.toBuilder();
              }
              server_ = input.readMessage(com.pkslow.proto.PkslowWebSite.WebSite.Server.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(server_);
                server_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pkslow.proto.PkslowWebSite.WebSite.class, com.pkslow.proto.PkslowWebSite.WebSite.Builder.class);
    }

    public interface ServerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:WebSite.Server)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string hostname = 1;</code>
       * @return The hostname.
       */
      java.lang.String getHostname();
      /**
       * <code>string hostname = 1;</code>
       * @return The bytes for hostname.
       */
      com.google.protobuf.ByteString
          getHostnameBytes();

      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      int getPort();
    }
    /**
     * Protobuf type {@code WebSite.Server}
     */
    public static final class Server extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WebSite.Server)
        ServerOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Server.newBuilder() to construct.
      private Server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Server() {
        hostname_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Server();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Server(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                hostname_ = s;
                break;
              }
              case 16: {

                port_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_Server_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pkslow.proto.PkslowWebSite.WebSite.Server.class, com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder.class);
      }

      public static final int HOSTNAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object hostname_;
      /**
       * <code>string hostname = 1;</code>
       * @return The hostname.
       */
      @java.lang.Override
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostname_ = s;
          return s;
        }
      }
      /**
       * <code>string hostname = 1;</code>
       * @return The bytes for hostname.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PORT_FIELD_NUMBER = 2;
      private int port_;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getHostnameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostname_);
        }
        if (port_ != 0) {
          output.writeInt32(2, port_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getHostnameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostname_);
        }
        if (port_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, port_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.pkslow.proto.PkslowWebSite.WebSite.Server)) {
          return super.equals(obj);
        }
        com.pkslow.proto.PkslowWebSite.WebSite.Server other = (com.pkslow.proto.PkslowWebSite.WebSite.Server) obj;

        if (!getHostname()
            .equals(other.getHostname())) return false;
        if (getPort()
            != other.getPort()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getHostname().hashCode();
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.pkslow.proto.PkslowWebSite.WebSite.Server parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.pkslow.proto.PkslowWebSite.WebSite.Server prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code WebSite.Server}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:WebSite.Server)
          com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_Server_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_Server_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.pkslow.proto.PkslowWebSite.WebSite.Server.class, com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder.class);
        }

        // Construct using com.pkslow.proto.PkslowWebSite.WebSite.Server.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          hostname_ = "";

          port_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_Server_descriptor;
        }

        @java.lang.Override
        public com.pkslow.proto.PkslowWebSite.WebSite.Server getDefaultInstanceForType() {
          return com.pkslow.proto.PkslowWebSite.WebSite.Server.getDefaultInstance();
        }

        @java.lang.Override
        public com.pkslow.proto.PkslowWebSite.WebSite.Server build() {
          com.pkslow.proto.PkslowWebSite.WebSite.Server result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.pkslow.proto.PkslowWebSite.WebSite.Server buildPartial() {
          com.pkslow.proto.PkslowWebSite.WebSite.Server result = new com.pkslow.proto.PkslowWebSite.WebSite.Server(this);
          result.hostname_ = hostname_;
          result.port_ = port_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.pkslow.proto.PkslowWebSite.WebSite.Server) {
            return mergeFrom((com.pkslow.proto.PkslowWebSite.WebSite.Server)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.pkslow.proto.PkslowWebSite.WebSite.Server other) {
          if (other == com.pkslow.proto.PkslowWebSite.WebSite.Server.getDefaultInstance()) return this;
          if (!other.getHostname().isEmpty()) {
            hostname_ = other.hostname_;
            onChanged();
          }
          if (other.getPort() != 0) {
            setPort(other.getPort());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.pkslow.proto.PkslowWebSite.WebSite.Server parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.pkslow.proto.PkslowWebSite.WebSite.Server) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object hostname_ = "";
        /**
         * <code>string hostname = 1;</code>
         * @return The hostname.
         */
        public java.lang.String getHostname() {
          java.lang.Object ref = hostname_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            hostname_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string hostname = 1;</code>
         * @return The bytes for hostname.
         */
        public com.google.protobuf.ByteString
            getHostnameBytes() {
          java.lang.Object ref = hostname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            hostname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string hostname = 1;</code>
         * @param value The hostname to set.
         * @return This builder for chaining.
         */
        public Builder setHostname(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          hostname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string hostname = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearHostname() {
          
          hostname_ = getDefaultInstance().getHostname();
          onChanged();
          return this;
        }
        /**
         * <code>string hostname = 1;</code>
         * @param value The bytes for hostname to set.
         * @return This builder for chaining.
         */
        public Builder setHostnameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          hostname_ = value;
          onChanged();
          return this;
        }

        private int port_ ;
        /**
         * <code>int32 port = 2;</code>
         * @return The port.
         */
        @java.lang.Override
        public int getPort() {
          return port_;
        }
        /**
         * <code>int32 port = 2;</code>
         * @param value The port to set.
         * @return This builder for chaining.
         */
        public Builder setPort(int value) {
          
          port_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 port = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPort() {
          
          port_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:WebSite.Server)
      }

      // @@protoc_insertion_point(class_scope:WebSite.Server)
      private static final com.pkslow.proto.PkslowWebSite.WebSite.Server DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.pkslow.proto.PkslowWebSite.WebSite.Server();
      }

      public static com.pkslow.proto.PkslowWebSite.WebSite.Server getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Server>
          PARSER = new com.google.protobuf.AbstractParser<Server>() {
        @java.lang.Override
        public Server parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Server(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Server> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Server> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.pkslow.proto.PkslowWebSite.WebSite.Server getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINK_FIELD_NUMBER = 2;
    private volatile java.lang.Object link_;
    /**
     * <code>string link = 2;</code>
     * @return The link.
     */
    @java.lang.Override
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        link_ = s;
        return s;
      }
    }
    /**
     * <code>string link = 2;</code>
     * @return The bytes for link.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int SERVER_FIELD_NUMBER = 4;
    private com.pkslow.proto.PkslowWebSite.WebSite.Server server_;
    /**
     * <code>.WebSite.Server server = 4;</code>
     * @return Whether the server field is set.
     */
    @java.lang.Override
    public boolean hasServer() {
      return server_ != null;
    }
    /**
     * <code>.WebSite.Server server = 4;</code>
     * @return The server.
     */
    @java.lang.Override
    public com.pkslow.proto.PkslowWebSite.WebSite.Server getServer() {
      return server_ == null ? com.pkslow.proto.PkslowWebSite.WebSite.Server.getDefaultInstance() : server_;
    }
    /**
     * <code>.WebSite.Server server = 4;</code>
     */
    @java.lang.Override
    public com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder getServerOrBuilder() {
      return getServer();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getLinkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, link_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (server_ != null) {
        output.writeMessage(4, getServer());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getLinkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, link_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (server_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getServer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.pkslow.proto.PkslowWebSite.WebSite)) {
        return super.equals(obj);
      }
      com.pkslow.proto.PkslowWebSite.WebSite other = (com.pkslow.proto.PkslowWebSite.WebSite) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getLink()
          .equals(other.getLink())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (hasServer() != other.hasServer()) return false;
      if (hasServer()) {
        if (!getServer()
            .equals(other.getServer())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LINK_FIELD_NUMBER;
      hash = (53 * hash) + getLink().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasServer()) {
        hash = (37 * hash) + SERVER_FIELD_NUMBER;
        hash = (53 * hash) + getServer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.pkslow.proto.PkslowWebSite.WebSite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pkslow.proto.PkslowWebSite.WebSite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WebSite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WebSite)
        com.pkslow.proto.PkslowWebSite.WebSiteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pkslow.proto.PkslowWebSite.WebSite.class, com.pkslow.proto.PkslowWebSite.WebSite.Builder.class);
      }

      // Construct using com.pkslow.proto.PkslowWebSite.WebSite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        link_ = "";

        age_ = 0;

        if (serverBuilder_ == null) {
          server_ = null;
        } else {
          server_ = null;
          serverBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pkslow.proto.PkslowWebSite.internal_static_WebSite_descriptor;
      }

      @java.lang.Override
      public com.pkslow.proto.PkslowWebSite.WebSite getDefaultInstanceForType() {
        return com.pkslow.proto.PkslowWebSite.WebSite.getDefaultInstance();
      }

      @java.lang.Override
      public com.pkslow.proto.PkslowWebSite.WebSite build() {
        com.pkslow.proto.PkslowWebSite.WebSite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.pkslow.proto.PkslowWebSite.WebSite buildPartial() {
        com.pkslow.proto.PkslowWebSite.WebSite result = new com.pkslow.proto.PkslowWebSite.WebSite(this);
        result.name_ = name_;
        result.link_ = link_;
        result.age_ = age_;
        if (serverBuilder_ == null) {
          result.server_ = server_;
        } else {
          result.server_ = serverBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pkslow.proto.PkslowWebSite.WebSite) {
          return mergeFrom((com.pkslow.proto.PkslowWebSite.WebSite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pkslow.proto.PkslowWebSite.WebSite other) {
        if (other == com.pkslow.proto.PkslowWebSite.WebSite.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getLink().isEmpty()) {
          link_ = other.link_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasServer()) {
          mergeServer(other.getServer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pkslow.proto.PkslowWebSite.WebSite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pkslow.proto.PkslowWebSite.WebSite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object link_ = "";
      /**
       * <code>string link = 2;</code>
       * @return The link.
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string link = 2;</code>
       * @return The bytes for link.
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string link = 2;</code>
       * @param value The link to set.
       * @return This builder for chaining.
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        link_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string link = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLink() {
        
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      /**
       * <code>string link = 2;</code>
       * @param value The bytes for link to set.
       * @return This builder for chaining.
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        link_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.pkslow.proto.PkslowWebSite.WebSite.Server server_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pkslow.proto.PkslowWebSite.WebSite.Server, com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder, com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder> serverBuilder_;
      /**
       * <code>.WebSite.Server server = 4;</code>
       * @return Whether the server field is set.
       */
      public boolean hasServer() {
        return serverBuilder_ != null || server_ != null;
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       * @return The server.
       */
      public com.pkslow.proto.PkslowWebSite.WebSite.Server getServer() {
        if (serverBuilder_ == null) {
          return server_ == null ? com.pkslow.proto.PkslowWebSite.WebSite.Server.getDefaultInstance() : server_;
        } else {
          return serverBuilder_.getMessage();
        }
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public Builder setServer(com.pkslow.proto.PkslowWebSite.WebSite.Server value) {
        if (serverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          server_ = value;
          onChanged();
        } else {
          serverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public Builder setServer(
          com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder builderForValue) {
        if (serverBuilder_ == null) {
          server_ = builderForValue.build();
          onChanged();
        } else {
          serverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public Builder mergeServer(com.pkslow.proto.PkslowWebSite.WebSite.Server value) {
        if (serverBuilder_ == null) {
          if (server_ != null) {
            server_ =
              com.pkslow.proto.PkslowWebSite.WebSite.Server.newBuilder(server_).mergeFrom(value).buildPartial();
          } else {
            server_ = value;
          }
          onChanged();
        } else {
          serverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public Builder clearServer() {
        if (serverBuilder_ == null) {
          server_ = null;
          onChanged();
        } else {
          server_ = null;
          serverBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder getServerBuilder() {
        
        onChanged();
        return getServerFieldBuilder().getBuilder();
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      public com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder getServerOrBuilder() {
        if (serverBuilder_ != null) {
          return serverBuilder_.getMessageOrBuilder();
        } else {
          return server_ == null ?
              com.pkslow.proto.PkslowWebSite.WebSite.Server.getDefaultInstance() : server_;
        }
      }
      /**
       * <code>.WebSite.Server server = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.pkslow.proto.PkslowWebSite.WebSite.Server, com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder, com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder> 
          getServerFieldBuilder() {
        if (serverBuilder_ == null) {
          serverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.pkslow.proto.PkslowWebSite.WebSite.Server, com.pkslow.proto.PkslowWebSite.WebSite.Server.Builder, com.pkslow.proto.PkslowWebSite.WebSite.ServerOrBuilder>(
                  getServer(),
                  getParentForChildren(),
                  isClean());
          server_ = null;
        }
        return serverBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WebSite)
    }

    // @@protoc_insertion_point(class_scope:WebSite)
    private static final com.pkslow.proto.PkslowWebSite.WebSite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pkslow.proto.PkslowWebSite.WebSite();
    }

    public static com.pkslow.proto.PkslowWebSite.WebSite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebSite>
        PARSER = new com.google.protobuf.AbstractParser<WebSite>() {
      @java.lang.Override
      public WebSite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebSite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebSite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebSite> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.pkslow.proto.PkslowWebSite.WebSite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSite_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSite_Server_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSite_Server_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWebSite.proto\"}\n\007WebSite\022\014\n\004name\030\001 \001(\t" +
      "\022\014\n\004link\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\037\n\006server\030\004 " +
      "\001(\0132\017.WebSite.Server\032(\n\006Server\022\020\n\010hostna" +
      "me\030\001 \001(\t\022\014\n\004port\030\002 \001(\005B\'\n\020com.pkslow.pro" +
      "toB\rPkslowWebSite\240\001\001\330\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WebSite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WebSite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSite_descriptor,
        new java.lang.String[] { "Name", "Link", "Age", "Server", });
    internal_static_WebSite_Server_descriptor =
      internal_static_WebSite_descriptor.getNestedTypes().get(0);
    internal_static_WebSite_Server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSite_Server_descriptor,
        new java.lang.String[] { "Hostname", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
