spring:
  application:
    name: Springboot-Common

pkslow:
  condition:
    max: 1000
    min: 50
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug